name    'sbadia-metche'
version '0.0.2'
source  'https://github.com/sbadia/puppet-metche'
author  'Sebastien Badia'
license 'GPLv3'
summary 'Puppet Metche Module'
description 'Module to install/manage Metche using puppet'
project_page 'https://github.com/sbadia/puppet-metche/'
